// utils/errorHandler.js

class AppError extends Error {
    constructor(message, statusCode) {
        super(message);
        this.statusCode = statusCode;
        this.status = `${statusCode}`.startsWith('4') ? 'fail' : 'error';
        this.isOperational = true;

        Error.captureStackTrace(this, this.constructor);
    }
}

const handleError = (err, res) => {
    if (err.isOperational) {
        return res.status(err.statusCode).json({
            status: err.status,
            message: err.message
        });
    }
    
    // Programming or unknown errors: don't leak error details
    console.error('ERROR ðŸ’¥', err);
    return res.status(500).json({
        status: 'error',
        message: 'Something went wrong!'
    });
};

const asyncHandler = (fn) => {
    return (req, res, next) => {
        Promise.resolve(fn(req, res, next)).catch((err) => {
            handleError(err, res);
        });
    };
};

module.exports = {
    AppError,
    handleError,
    asyncHandler
};